# Generated by Django 3.1.1 on 2020-09-24 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://house.utah.gov/wp-content/uploads/2019/01/Image-Coming-Soon.jpg', max_length=500),
        ),
    ]
