# Generated by Django 3.1.1 on 2020-10-14 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_auto_20201013_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://www.fnasafety.com/wp-content/uploads/2016/04/ComingSoon2-fnasafety.png', max_length=500),
        ),
    ]
